#!/usr/bin/env bash
# Script that ensures Nginx listens on port 80

# Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80
# Solution: https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80

# Adjust Nginx configuration to listen on port 80
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo sed -i 's/^ *listen *80;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
